# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: sv-SE

reviews:
  profile: chill
  auto_review:
    enabled: true
    drafts: false
  poem: false
  finishing_touches: false
